stages:
 - test
 - release

variables:
  PYPI_CONFIG: |
    [distutils]
    index-servers = kiwi

    [kiwi]
    repository: https://pypi.skypicker.com/pypi/
    username: $PYPI_USERNAME
    password: $PYPI_PASSWORD

.test-with-artifacts: &test-with-artifacts
  image: kiwicom/tox:3.2
  stage: test
  services:
    - postgres:10.5
  variables:
    ENV_NAME: null

  script:
   - mkdir -p reports
   - export DATABASE_URI=postgres://postgres:postgres@$POSTGRES_PORT_5432_TCP_ADDR:5432/postgres
   - tox -e $ENV_NAME -- --junitxml=reports/$ENV_NAME/test_report.xml --cov kw --cov-report xml --cov-config .coveragerc --cov-append --cov-report xml:reports/coverage.xml

  artifacts:
    untracked: true
    expire_in: 12h
    paths:
      - reports/
  cache:
    paths:
      - .tox/
      - reports/
    key: $CI_COMMIT_REF_SLUG

python-3.6:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py36

python-3.6-simplejson:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py36_with_simplejson

python-3.7:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py37

python2.7:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py27

python2.7-enums:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py27_with_enum

pylint:
  image: themattrix/tox
  stage: test
  script:
   - tox -e pylint

black:
  image: kiwicom/black:18.6b4
  stage: test
  variables:
    MODULES: kw test setup.py

  script:
   - black -l 120 --py36 --check --diff $MODULES

coala:
  stage: test
  image: coala/base:0.11
  script:
   - coala --non-interactive

release:
  stage: release
  image: python:3.6-alpine
  script:
   - echo "$PYPI_CONFIG" > ~/.pypirc
   - pip install wheel
   - python setup.py bdist_wheel --universal upload -r kiwi
  only:
   - master
  allow_failure: yes  # always runs but fails if there's already a release for the version
