stages:
 - test
 - release

include:
  - 'https://ci-files.skypicker.com/templates/release/pypi_upload.yml'
  - 'https://ci-files.skypicker.com/templates/build/black.yml'
  - 'https://ci-files.skypicker.com/templates/build/coala.yml'

.test-with-artifacts: &test-with-artifacts
  image: kiwicom/tox:3.12
  stage: test
  services:
    - postgres:10.5
  variables:
    ENV_NAME: null

  script:
   - mkdir -p reports
   - export DATABASE_URI=postgres://postgres:postgres@$POSTGRES_PORT_5432_TCP_ADDR:5432/postgres
   - tox -e $ENV_NAME -- --junitxml=reports/$ENV_NAME/test_report.xml --cov kw --cov-report xml --cov-config .coveragerc --cov-append --cov-report xml:reports/coverage.xml

  artifacts:
    untracked: true
    expire_in: 12h
    paths:
      - reports/
  cache:
    paths:
      - .tox/
      - reports/
    key: $CI_COMMIT_REF_SLUG

python-3.6:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py36

python-3.6-simplejson:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py36_with_simplejson

python-3.7:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py37

python2.7:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py27

python2.7-enums:
  <<: *test-with-artifacts
  variables:
    ENV_NAME: py27_with_enum

pylint:
  image: kiwicom/tox:3.12
  stage: test
  script:
   - tox -e pylint

black:
  stage: test
  script:
   - black -l 120 --py36 --check --diff $MODULES

coala:
  stage: test

pypi_upload:
  only:
    changes:
      - setup.py

